services:
  - type: web
    name: sport-transmissions-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    healthCheckPath: "/transmissions"
    envVars:
      - key: FLASK_ENV
        value: production
    branches:
      - main
